# Generated by Django 5.2 on 2025-04-05 09:47

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='body',
            new_name='footer',
        ),
        migrations.AddField(
            model_name='homepage',
            name='body_content',
            field=wagtail.fields.StreamField([('richtext', 0), ('image', 1)], blank=True, block_lookup={0: ('cms_blocks.models.BodyRichTextBlock', (), {}), 1: ('wagtail.images.blocks.ImageBlock', [], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='intro',
            field=wagtail.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='links',
            field=wagtail.fields.StreamField([('link', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "e.g. 'fa-solid fa-briefcase'", 'required': False}), 2: ('wagtail.blocks.PageChooserBlock', (), {'required': False}), 3: ('wagtail.blocks.URLBlock', (), {'required': False}), 4: ('wagtail.blocks.StructBlock', [[('title', 0), ('icon', 1), ('page', 2), ('external_url', 3)]], {})}),
        ),
        migrations.AddField(
            model_name='homepage',
            name='subheader',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
