# Generated by Django 5.2 on 2025-04-05 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_location_city_location_country_location_postal_code_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['name']},
        ),
    ]
